name: Deploy

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: cd ${{ secrets.PATH }} && ./deploy.sh
          
      - name: Build status webhook
        if: always()
        run: |
          git clone https://github.com/Encode42/discord-workflows-webhook.git webhook
          bash webhook/send.sh ${{ job.status }} ${{ secrets.WEBHOOK_URL }}
        shell: bash
